### PR TITLE
Updated user.schema.ts

### PR DESCRIPTION
**Pull request by PrajnaKC**
Added required id and password fields.
Ensured username is unique and required.
Included preferences to store favorite and disliked genres.
Added watch History to track user's watched content with ratings.

### CODE REVIEW

**Review by aayushai — APPROVED** [review]

**Review by aayushai — APPROVED** [review]

**Comment by aayushai** [comment]
@PrajnaKC Good commit, If you have knowledge about this topic in depth do checkout other issue like #2 and #3 .

**Comment by PrajnaKC** [comment]
Thank you! I'll take a look at issues #2 and #3 as well .

**Comment by PrajnaKC** [comment]
@aayushai 
Thank you for merging my pull request! I will try to check out issues #2 and #3 as well.
I noticed that I didn’t receive a relevant label for it. Could you please assign the appropriate label .
Thanks again for your time and support!

**Comment by PrajnaKC** [comment]
Thank you! I will check out other issues as well.

**Pull request merged**
